spring.application.name=Template_Workflow
spring.datasource.url=jdbc:postgresql://localhost:5432/MasterThesis_Workflow
spring.datasource.username=postgres
spring.datasource.password=postgres_postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update